console.time('Your code took time');
console.log("This is console");
console.log(20+5);
console.log(43-2);
console.log(43*2);
console.log(43/2);
console.log(43%2);
console.log(true);
console.log([2,4,6,7,4,9]);
console.log({nadeem:'This', marks:92});
console.table({nadeem:'This', marks:92});
console.warn("This is large warning");
// console.clear();
console.timeEnd('Your code took time');
console.assert(160<150, 'Age>150 is not possible');
console.error("This is an errors");